feat: Add HTML documentation files for project documentation
DD2480-Group-15-vt24/2-CI pull request #26
Opened 2024-02-13 18:04 UTC by selmaozdere

2024-02-13 18:10 UTC, ollisco requested changes
Remove the `.DS_Store` files since they are just MacOS specific files.

2024-02-13 18:43 UTC, lolindgr requested changes
main.py should also have its own HTML file

2024-02-13 18:56 UTC, lolindgr approved these changes

2024-02-14 08:48 UTC, ollisco approved these changes
Nice!

2024-02-14 08:49 UTC, merged